server: # for eureka clients
  port: 8081

spring:
  application:
    name: ecommerce-service
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Enable discovery-based routing