spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Enable discovery-based routing

server:
  port: 8671

# Optional: To customize routes without discovery, example:
# spring:
#   cloud:
#     gateway:
#       routes:
#         - id: some-service
#           uri: lb://some-service
#           predicates:
#             - Path=/some-service/**
